# Generated by Django 3.2 on 2021-05-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
        ('kehadiran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='jenis_kehadiran',
            field=models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti'), ('alpa', 'Tanpa Alasan'), ('hadir', 'Hadir')], default='hadir', max_length=20),
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.karyawan'),
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='waktu',
            field=models.DateField(null=True),
        ),
    ]
