# Generated by Django 3.2 on 2021-05-31 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
        ('kehadiran', '0002_auto_20210524_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='waktu',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kehadiran', models.CharField(choices=[('izin', 'Izin'), ('cuti', 'Cuti')], max_length=20)),
                ('waktu_mulai', models.DateField()),
                ('waktu_berhenti', models.DateField()),
                ('alasan', models.TextField()),
                ('disetujui', models.BooleanField(default=False)),
                ('karyawan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.karyawan')),
            ],
        ),
    ]
